services:
  db:
    image:
      postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always

